# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='blog/images/tree.png', upload_to='blog/images/'),
        ),
    ]
